### ISSUE TITLE
Package seems to be broken, not getting any responses back from the API

### ISSUE THREAD

**Issue by Diniboy1123** [pavel-one/EdgeGPT-Go#13]
Hi,

The title speaks for itself. For a bit of time the library has stopped working for me. I saw that similar projects migrated to `https://www.bing.com/turing/conversation/create` and started spoofing residential IPs, but neither helped for me.

Does it work for you?

Edit: Apparently the URL change is necessary and after that you need to solve a captcha in browser and export cookies afterwards. Then it works fine.

**Comment by pavel-one** [comment]
Hello, yes, everything works. As you noticed, now you need to solve the captcha before exporting cookies. Also everything works with the old url for conversation.
