### ISSUE TITLE
 stopped after 10 redirects

### ISSUE THREAD

**Issue by f1ndm1** [pavel-one/EdgeGPT-Go#4]
HOW TO DEAL Get "https://cn.bing.com/edgesvc/turing/conversation/create": stopped after 10 redirects ？
![image](https://user-images.githubusercontent.com/60958190/231376425-2ca00e55-3a3b-4e36-a432-6aa246603856.png)

**Comment by f1ndm1** [comment]
didn't init GPT service

**Comment by pavel-one** [comment]
Try changing this url `https://cn.bing.com/edgesvc/turing/conversation/create` to `https://edge.churchless.tech/edgesvc/turing/conversation/create` please report if it works

**Comment by f1ndm1** [comment]
thank u bro！But there is another question I need to ask you, how to adjust the model I asked is the most accurate rather than imaginative？Where can I set this?

**Comment by pavel-one** [comment]
https://github.com/pavel-one/EdgeGPT-Go/blob/master/hub.go#L74 Only in source code.
All styles here: https://github.com/pavel-one/EdgeGPT-Go/blob/master/gpt.go#L21-L23
I make it a setting in the next release

**Comment by CoconuterTATA** [comment]
Hi，I met the same problem:2023-04-24T00:48:28.551+0800	INFO	CookieManager/manager.go:78	Getting new cookies: ./cookies/1.json
2023/04/24 00:48:31 didn't init GPT service: Get "https://cn.bing.com/edgesvc/turing/conversation/create": stopped after 10 redirects
exit status 1
plz,tell me how to change this url? thank you!

**Comment by cherryReptile** [comment]
Hi, you can set CONVERSATION_ENDPOINT in your env to resolve this problem

**Comment by CoconuterTATA** [comment]
I guess maybe my ip cant get access to newbing. So, Can I set proxy to access? If it can, plz tell me how to set in code. My proxy port is localhost:7890. Thank you

> Hi, you can set CONVERSATION_ENDPOINT in your env to resolve this problem

**Comment by pavel-one** [comment]
@f1ndm1 @CoconuterTATA added to readme, only for use v1.3.0, please check it
